apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: banco-de-dados-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banco-de-dados
  template:
    metadata:
      labels:
        app: banco-de-dados
    spec:
      containers:
        - name: banco-de-dados
          image: gaellopes/banco-it-talent:v1  
          ports:
            - containerPort: 3306 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"  


